services:
  - type: web
    name: customermind
    runtime: python
    pythonVersion: 3.8
    startCommand: python app.py
    envVars:
      - key: MONGO_DB_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.8.10
